
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class rideover extends javax.swing.JFrame {

    Connection connect= null;
    String runame;
    String rname;
    String driver_givenuid;
    int driver_count;
    double driver_rating;
     PreparedStatement st1=null,smt=null,pst1=null,ps=null,pstmt=null,pst2=null;
    ResultSet rs1,rs,rs2,rs3;
    public rideover(String user_id, String driver_uid) {
        initComponents();
        runame=user_id;
        driver_givenuid=driver_uid;
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(Submit);
        connect=dbm.dbconnect();
         String query2="select * from cust where user_id=?";
        PreparedStatement ps1=null;
        try {
            ps1 = connect.prepareStatement(query2);
            ps1.setString(1, user_id);
            rs3=ps1.executeQuery();
             while(rs3.next()) {
                rname = rs3.getString("name");
            }
            //rname=rs3.getString("name");
            hi_name.setText("Hi, "+rname);}
         catch (SQLException ex) {
           // System.out.println("Entered");
            System.out.println("hello");                    // DOubt??//
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hi_name = new javax.swing.JLabel();
        rating = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Your Ride is over. Thankyou for choosing us. Please give your valuable feedback");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel3.setText("Rating:");

        hi_name.setText("Hello XYZ!");

        rating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));
        rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gotham Medium", 1, 36)); // NOI18N
        jLabel14.setText("Book My Cab 2.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hi_name, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(Submit)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(hi_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int rate=rating.getSelectedIndex();
        
        String query_ini="select * from driver where uid=?";
        PreparedStatement ps_ini=null;

        try {
            ps_ini = connect.prepareStatement(query_ini);
            ps_ini.setString(1, driver_givenuid);
            ResultSet rs_ini=ps_ini.executeQuery();
            while(rs_ini.next()) {
                driver_count=rs_ini.getInt("count");
                driver_rating=rs_ini.getDouble("rating");
            }
         }catch (SQLException ex) {
            System.out.println("Entered");
            System.out.println(ex.getMessage());                    // DOubt??//
        }    
        
        PreparedStatement ps1=null;
        try{
            String query="update driver set rating=? where uid = ?";
            ps1=connect.prepareStatement(query);
            
            driver_rating= (driver_rating*(driver_count-1) + (5-rate))/driver_count;
            
            ps1.setDouble(1,driver_rating);
            ps1.setString(2, driver_givenuid);
            ps1.execute();
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null ,e);
         }
        this.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    private void ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingActionPerformed
             
    }//GEN-LAST:event_ratingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel hi_name;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> rating;
    // End of variables declaration//GEN-END:variables
}
